services:
  stereo-vo:
    image: vri-ufpr/stereo-vo:latest
    container_name: stereo-vo
    privileged: true
    ipc: host
    network_mode: host
    volumes:
      - .:/workspace/
      - /tmp.X11-unix:/tmp/.X11-unix
      - /dev:/dev
      - /tmp/argus_socket:/tmp/argus_socket
      - $HOME/.Xauthority:/root/.Xauthority:rw
    command: tail -f /dev/null # Keep container running

  foxglove-bridge:
    image: foxglove/bridge:ros2
    container_name: foxglove-bridge
    network_mode: host
