%YAML 1.0

sensors:
  imu:
    topic: "/sensors/bno08x/raw"
    sample_rate: 300
    bus: 1

  cameras:
    topic: "/sensors/imx/image_stereo"
    publish_visualization_msgs: 0
    visualization_msgs_topic: "/sensors/imx/viz"
    devices:
      - sample_rate: 30
        input_stream: "csi://0"
        resolution:
          width: 640
          height: 480

      - sample_rate: 30
        input_stream: "csi://1"
        resolution:
          width: 640
          height: 480

stereo_vo:
  stereo_image_topic: "/sensors/imx/image_stereo"
  right_cam_intrinsics: "/workspace/config/imx_right_intrinsics.yaml"
  left_cam_intrinsics: "/workspace/config/imx_left_intrinsics.yaml"

  depth_estimator_service: "/stereo_vo/depth_estimation"
  feature_extractor_service: "/stereo_vo/feature_extraction"
  feature_matcher_service: "/stereo_vo/feature_matching"