%YAML 1.0

sensors:
  imu:
    topic: "/sensors/bno08x/raw"
    sample_rate: 300
    bus: 1

  cameras:
    devices:
      - sample_rate: 30
        topic: "/sensors/imx_left/image_raw"
        input_stream: "csi://0"
        resolution:
          width: 640
          height: 480

      - sample_rate: 30
        topic: "/sensors/imx_right/image_raw"
        input_stream: "csi://1"
        resolution:
          width: 640
          height: 480

stereo_vo:
  left_cam:
    topic: "/sensors/imx_left/image_raw"
    intrinsics_file: "/workspace/config/imx_left_intrinsics.yaml"

  right_cam:
    topic: "/sensors/imx_right/image_raw"
    intrinsics_file: "/workspace/config/imx_right_intrinsics.yaml"

  depth_estimator_service: "/stereo_vo/depth_estimation"
  num_disparities: 64
  block_size: 21  # Must be odd

  feature_extractor_service: "/stereo_vo/feature_extraction"
  feature_matcher_service: "/stereo_vo/feature_matching"

  image_size:
    width: 640
    height: 480