# Filename of the configuration file without .yaml
preset: "kitti"

stereo_vo:
  debug_visualization: true
  reprojection_threshold: 50.0

depth_estimator_params:    

  depth_algorithm: "cuda_bm"  # stereo_bm, stereo_sgbm, cuda_bm, belief_propagation, constant_space_bp

  # Algorithm specific parameters
  # Set to -1 to use default/recommended values by OpenCV 
  # (refer to https://docs.opencv.org/3.4/d2/d6e/classcv_1_1StereoMatcher.html)
  num_disparities: 56  # Must be divisible by 8
  block_size: 5  # Must be odd
  iterations: 3
  levels: 3
  nr_plane: 4

feature_matcher:
  distance_threshold: 20.0
  grid_factor: 1