# Filename of the configuration file without .yaml
preset: "ufpr_map"

stereo_vo:
  debug_visualization: true
  velocity_buffer_size: 10
  velocity_threshold: 15.0

depth_estimator_params:    

  depth_algorithm: "stereo_sgbm"  # stereo_bm, stereo_sgbm, cuda_bm, belief_propagation, constant_space_bp

  # Algorithm specific parameters
  # Set to -1 to use default/recommended values by OpenCV 
  # (refer to https://docs.opencv.org/3.4/d2/d6e/classcv_1_1StereoMatcher.html)
  num_disparities: 54
  block_size: 9  # Must be odd
  iterations: 3
  levels: 3
  nr_plane: 4