%YAML 1.0

sensors:
  imu:
    topic: "/sensors/bno08x/raw"
    sample_rate: 300
    bus: 1

  cameras:
    devices:
      - sample_rate: 30
        topic: "/sensors/imx_left/image_raw"
        input_stream: "csi://0"
        resolution:
          width: 640
          height: 480

      - sample_rate: 30
        topic: "/sensors/imx_right/image_raw"
        input_stream: "csi://1"
        resolution:
          width: 640
          height: 480

stereo_vo:

  odom_topic: "/stereo_vo/odom"
  ground_truth: "/leica/position"

  debug_visualization: 1
  depth_map_viz: "/stereo_vo/depth_map_viz"
  feature_viz: "/stereo_vo/feature_viz"

  estimate_depth: 1
  depth_topic: "/camera/depth/image"

  left_cam:
    topic: "/cam0/image_raw"
    intrinsics_file: "/workspace/config/euroc_0_intrinsics.yaml"

  right_cam:
    topic: "/cam1/image_raw"
    intrinsics_file: "/workspace/config/euroc_1_intrinsics.yaml"

  depth_estimator_params:
    topic: "/stereo_vo/depth_estimation"
    
    image_size:
      width: 752
      height: 480

    depth_algorithm: "stereo_sgbm"  # stereo_bm, stereo_sgbm, cuda_bm, belief_propagation, constant_space_bp

    # Algorithm specific parameters
    # Set to -1 to use default/recommended values by OpenCV 
    # (refer to https://docs.opencv.org/3.4/d2/d6e/classcv_1_1StereoMatcher.html)
    num_disparities: 54
    block_size: 9  # Must be odd
    iterations: 3
    levels: 3
    nr_plane: 4

  feature_extractor_service: "/stereo_vo/feature_extraction"