# Filename of the configuration file without .yaml
preset: "kitti"

stereo_vo:
  debug_visualization: true
  reprojection_threshold: 20.0

depth_estimator_params:
  depth_algorithm: "stereo_sgbm" # stereo_bm, stereo_sgbm, cuda_bm, cuda_sgm, belief_propagation, constant_space_bp

  # Algorithm specific parameters
  # Set to -1 to use default/recommended values by OpenCV
  # (refer to https://docs.opencv.org/3.4/d2/d6e/classcv_1_1StereoMatcher.html)
  num_disparities: 96 # Must be divisible by 8
  block_size: 11 # Must be odd
  sad_window: 6
  iterations: 3
  levels: 3
  nr_plane: 4

feature_matcher:
  extractor: "sift" # orb, sift
  distance_ratio: 0.3
