imu: false
camera: false
vo: true
depth: true
markers: true
bag: true

bag_name: "MH_01_easy_ros2"

sensors:
  imu:
    sample_rate: 300
    bus: 1

  cameras:
    left:
      - sample_rate: 30
        input_stream: ""
    right:
      - sample_rate: 30
        input_stream: ""

im_size:
  width: 640
  height: 480

baseline: 0.11004592927 

undistort: true

left_cam:
  topic: "/cam0/image_raw"
  intrinsics_file: "/workspace/config/intrinsics/euroc_0_intrinsics.yaml"

right_cam:
  topic: "/cam1/image_raw"
  intrinsics_file: "/workspace/config/intrinsics/euroc_1_intrinsics.yaml"

vo_odom_topic: "/stereo_vo/odom"
feature_viz: "/stereo_vo/feature_viz"

depth_topic: "/stereo_vo/depth_estimation"

feature_extractor_service: "/stereo_vo/feature_extraction"

ground_truth: "/leica/position"