imu: false
camera: true
vo: true
depth: true
markers: true
bag: false

bag_name: ""
bag_rate: 1.0

sensors:
  imu:
    sample_rate: 300
    bus: 1

  cameras:
    left:
      - sample_rate: 30
        input_stream: "csi://0"
    right:
      - sample_rate: 30
        input_stream: "csi://1"

im_size:
  width: 640
  height: 480

undistort: true

baseline: 0.03968711591

left_cam:
  topic: "/sensors/imx_right/image_raw"
  intrinsics_file: "/workspace/config/intrinsics/imx_left_intrinsics.yaml"

right_cam:
  topic: "/sensors/imx_right/image_raw"
  intrinsics_file: "/workspace/config/intrinsics/imx_rigth_intrinsics.yaml"

vo_odom_topic: "/stereo_vo/odom"
feature_viz: "/stereo_vo/feature_viz"
depth_viz: "/stereo_vo/depth_viz"

ground_truth: "/leica/position"
ground_truth_msg_type: "point"

odom_scale: [1.0, 1.0, 1.0]