imu: false
camera: false
vo: true
depth: true
markers: true
bag: true

bag_name: "kitti_data_odometry_gray_sequence_00-ros2_bag"
bag_rate: 1.0

sensors:
  imu:
    sample_rate: 300
    bus: 1

  cameras:
    left:
      - sample_rate: 30
        input_stream: ""
    right:
      - sample_rate: 30
        input_stream: ""

im_size:
  width: 1226
  height: 370

baseline: 0.5372

undistort: false

left_cam:
  topic: "/kitti/camera_gray_left/image_rect"
  intrinsics_file: "/workspace/config/intrinsics/kitti_left_intrinsics.yaml"

right_cam:
  topic: "/kitti/camera_gray_right/image_rect"
  intrinsics_file: "/workspace/config/intrinsics/kitti_right_intrinsics.yaml"

vo_odom_topic: "/stereo_vo/odom"
feature_viz: "/stereo_vo/feature_viz"
depth_viz: "/stereo_vo/depth_viz"

ground_truth: "/tf"
ground_truth_msg_type: "transform"

odom_scale: [10.0, 0.0, 10.0]
