imu: false
camera: false
vo: true
depth: true
markers: true
bag: true

bag_name: "kitti_data_odometry_gray_sequence_05-ros2_bag"

sensors:
  imu:
    sample_rate: 300
    bus: 1

  cameras:
    left:
      - sample_rate: 30
        input_stream: ""
    right:
      - sample_rate: 30
        input_stream: ""

im_size:
  width: 1226
  height: 370

baseline: 0.537

undistort: false

left_cam:
  topic: "/kitti/camera_gray_left/image_rect"
  intrinsics_file: "/workspace/config/intrinsics/kitti_left_intrinsics.yaml"

right_cam:
  topic: "/kitti/camera_gray_right/image_rect"
  intrinsics_file: "/workspace/config/intrinsics/kitti_right_intrinsics.yaml"

vo_odom_topic: "/stereo_vo/odom"
feature_viz: "/stereo_vo/feature_viz"
depth_viz: "/stereo_vo/depth_viz"

depth_estimation_service: "/stereo_vo/depth_estimation"

feature_extractor_service: "/stereo_vo/feature_extraction"

ground_truth: "/leica/position"