imu: false
camera: false
vo: true
depth: false
markers: true
bag: true

bag_name: "dataset_vri4wd_ufpr-map_20230830s001ab_ros2-bag"

sensors:
  imu:
    sample_rate: 300
    bus: 1

  cameras:
    left:
      - sample_rate: 30
        input_stream: ""
    right:
      - sample_rate: 30
        input_stream: ""

im_size:
  width: 640
  height: 480

undistort: true

baseline: 0.075

left_cam:
  topic: "/camera/rgb/image_mono"
  intrinsics_file: "/workspace/config/intrinsics/kinetic_intrinsics.yaml"

right_cam:
  topic: "/camera/rgb/image_mono"
  intrinsics_file: "/workspace/config/intrinsics/kinetic_intrinsics.yaml"

vo_odom_topic: "/stereo_vo/odom"
feature_viz: "/stereo_vo/feature_viz"
depth_viz: "/camera/depth/image"

depth_estimation_service: "/stereo_vo/depth_estimation"

feature_extractor_service: "/stereo_vo/feature_extraction"

ground_truth: "/leica/position"
ground_truth_msg_type: "point"

odom_scale: [1.0, 1.0, 1.0]